version: 0.0
os: linux
files:
  - source: /var/lib/jenkins/workspace/re-deploy/index.html
    destination: /var/www/html/hello
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
